### ISSUE TITLE
Is this on purpose?

### ISSUE THREAD

**Issue by saimonn** [HackYourOffice/coffee-recipe#1]
https://github.com/HackYourOffice/coffee-recipe/blob/6a15b16ca6ee8a9261a91255a4f44a3c8e0195d2/arduino/rfid_scanner.ino#L34

**Comment by derTobsch** [comment]
@saimonn the password will change automatically every day. So this is not critical for us. But thanks for pointing this out.

**Comment by saimonn** [comment]
great idea for a guest wifi! Sorry for the noise.
